Merge...

diff --git a/lib/libpcap/configure- b/lib/libpcap/configure-
--- a/lib/libpcap/configure-
+++ b/lib/libpcap/configure-
@@ -7232,6 +7232,18 @@ else
 fi
 
  	fi
+	{ echo "$as_me:$LINENO: result: $ac_cv_linux_vers" >&5
+echo "${ECHO_T}$ac_cv_linux_vers" >&6; }
+ 	if test $ac_cv_linux_vers = unknown ; then
+ 		{ { echo "$as_me:$LINENO: error: cannot determine linux version when cross-compiling" >&5
+echo "$as_me: error: cannot determine linux version when cross-compiling" >&2;}
+   { (exit 1); exit 1; }; }
+ 	fi
+	if test $ac_cv_linux_vers -lt 2 ; then
+		{ { echo "$as_me:$LINENO: error: version 2 or higher required; see the INSTALL doc for more info" >&5
+echo "$as_me: error: version 2 or higher required; see the INSTALL doc for more info" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
 
 	#
 	# Do we have the wireless extensions?
